version: '3.8'

services:
  app:
    build: .
    container_name: athletix-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - .env:/app/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - GIN_MODE=release
      - REDIS_HOST=redis  
      - REDIS_PORT=6379
    networks:
      - go-network

  db:
    image: postgres:15-alpine
    container_name: athletix-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: npg_0MTnS7LifqaP
      POSTGRES_DB: atletix
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d atletix"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - go-network

  redis:
    image: redis:7-alpine
    container_name: athletix-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - go-network

volumes:
  postgres_data:
  redis_data: 

networks:
  go-network:
    driver: bridge